// src/cubic/Layout/Titlebar.svelte
<!-- Titlebar.svelte -->
<script lang="ts">
    import { appStore } from "@stores/launcher";
    import { currentTheme } from "@stores/theme";
    import Logo from "@assets/Logo.svelte";
    import "../../css/titlebar.scss";
    import { getCurrentWindow } from "@tauri-apps/api/window";
    import {
        hideLauncher,
        closeLauncher,
        maximizeLauncher,
    } from "../libraries/backend";

    function startDrag() {
        getCurrentWindow().startDragging();
    }

    // Prevent dragging when clicking controls
    function stopPropagation(event: Event) {
        event.stopPropagation();
    }

    const background = $derived($currentTheme?.background);
    const currentInstance = $derived($appStore.currentInstance);
</script>

<div
    class="titlebar bg-[{background}]"
    onmousedown={startDrag}
    role="button"
    tabindex="-1"
>
    <!-- Left spacer for balance -->
    <div class="spacer"></div>
    <!-- Center content -->
    <div class="center-content">
        <Logo width="1.5rem" height="1.5rem" />
        {#if currentInstance}
            <span class="title-text">{`${currentInstance.name} - Cubic`}</span>
        {:else}
            <span class="title-text">Cubic</span>
        {/if}
    </div>
    <!-- Window controls -->
    <div
        class="window-controls"
        onmousedown={stopPropagation}
        role="button"
        tabindex="-1"
    >
        <button
            onclick={hideLauncher}
            class="control-button"
            aria-label="Minimize"
            onmousedown={stopPropagation}
        >
            <svg width="12" height="12" viewBox="0 0 12 12">
                <path
                    d="M3 6h6"
                    stroke="currentColor"
                    stroke-width="1.5"
                    stroke-linecap="round"
                />
            </svg>
        </button>
        <button
            onclick={maximizeLauncher}
            class="control-button"
            aria-label="Maximize"
            onmousedown={stopPropagation}
        >
            <svg width="12" height="12" viewBox="0 0 12 12">
                <rect
                    x="3"
                    y="3"
                    width="6"
                    height="6"
                    stroke="currentColor"
                    stroke-width="1.5"
                    fill="none"
                    rx="1"
                />
            </svg>
        </button>
        <button
            onclick={closeLauncher}
            class="control-button close-button"
            aria-label="Close"
            onmousedown={stopPropagation}
        >
            <svg width="12" height="12" viewBox="0 0 12 12">
                <path
                    d="M3 3l6 6M9 3l-6 6"
                    stroke="currentColor"
                    stroke-width="1.5"
                    stroke-linecap="round"
                />
            </svg>
        </button>
    </div>
</div>

// src/components/layout/Titlebar.vue
<script setup lang="ts">
import { useLauncherStore } from "../../stores/LauncherStore";
const store = useLauncherStore();
import { closeLauncher, hideLauncher, maximizeLauncher } from "../../api";
import logo from "../../assets/logo.vue";
import { getIcon } from "../../lib/utils";
</script>

<template>
  <div class="flex items-center justify-between h-9 bg-stone-800 border-b border-stone-600 px-4 titlebar z-1000">
    <!-- Left spacer for balance -->
    <div class="w-24"></div>

    <div class="flex items-center gap-2.5 px-3  bg-stone-750/30 rounded-md border border-stone-600/30">
      <component v-if="store.CurrentInstance" :is="getIcon(store.CurrentInstance.loader.loader)" class="w-6 h-6" />
      <logo v-else class="w-6 h-6" />

      <span class="text-sm text-stone-200 select-none">
        {{ store.CurrentInstance ? `${store.CurrentInstance.name} — Cubic` : 'CubicLauncher' }}
      </span>
    </div>

    <!-- Window controls -->
    <div class="flex items-center gap-0.5 titlebar-buttons">
      <button @click="hideLauncher()"
        class="w-7 h-7 flex items-center justify-center text-stone-400 hover:text-stone-200 hover:bg-stone-700 rounded-sm transition-all duration-75 no-drag"
        aria-label="Minimize">
        <svg width="12" height="12" viewBox="0 0 12 12">
          <path d="M3 6h6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
        </svg>
      </button>

      <button @click="maximizeLauncher()"
        class="w-7 h-7 flex items-center justify-center text-stone-400 hover:text-stone-200 hover:bg-stone-700 rounded-sm transition-all duration-75 no-drag"
        aria-label="Maximize">
        <svg width="12" height="12" viewBox="0 0 12 12">
          <rect x="3" y="3" width="6" height="6" stroke="currentColor" stroke-width="1.5" fill="none" rx="1" />
        </svg>
      </button>

      <button @click="closeLauncher()"
        class="w-7 h-7 flex items-center justify-center text-stone-400 hover:text-stone-200 hover:bg-stone-600 rounded-sm transition-all duration-75 no-drag"
        aria-label="Close">
        <svg width="12" height="12" viewBox="0 0 12 12">
          <path d="M3 3l6 6M9 3l-6 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
        </svg>
      </button>
    </div>
  </div>
</template>

<style scoped>
.titlebar {
  -webkit-app-region: drag;
  user-select: none;
}

.titlebar-buttons,
.no-drag {
  -webkit-app-region: no-drag;
}
</style>
