// src/cubic/components/sidebar/Sidebar.svelte
<script lang="ts">
    // TODO: Migrar a svelte 5
    import SidebarItem from "./SidebarItem.svelte";
    import SidebarTooltip from "./SidebarTooltip.svelte";
    import Logo from "@assets/Logo.svelte";
    import settings from "@assets/icons/UI/settings.svelte";
    import { appStore, instances } from "../../stores/launcher";
    import { isDarkTheme } from "../../stores/theme";

    $: items = $instances.map((instance) => {
        return {
            name: instance.name,
            icon: instance.icon,
            onClick: () => appStore.setCurrentInstance(instance),
        };
    });

    // Tooltip state
    let tooltipShow = false;
    let tooltipX = 0;
    let tooltipY = 0;
    let tooltipText = "";

    const showTooltip = (event: MouseEvent, text: string) => {
        const rect = (
            event.currentTarget as HTMLElement
        ).getBoundingClientRect();
        tooltipX = rect.right + 8;
        tooltipY = rect.top + rect.height / 2;
        tooltipText = text;
        tooltipShow = true;
    };

    const hideTooltip = () => {
        tooltipShow = false;
    };

    function handleLogoClick() {
        appStore.setCurrentInstance(null);
    }

    function handleSettingsClick() {
        appStore.handle_settings_modal();
    }
</script>

<div class="sidebar" class:dark={$isDarkTheme}>
    <div
        class="logo-container"
        on:click={handleLogoClick}
        on:mouseenter={(e) => showTooltip(e, "Home")}
        on:mouseleave={hideTooltip}
        role="button"
        tabindex="0"
        on:keydown={(e) => e.key === "Enter" && handleLogoClick()}
    >
        <Logo
            size="2rem"
            width="2rem"
            height="2rem"
            color={undefined}
            className=""
            id=""
        />
    </div>

    <div class="instances-container">
        <div class="instances-scroll">
            {#each items as item (item.name)}
                <SidebarItem Icon={item.icon} onClick={item.onClick} />
            {/each}
        </div>
    </div>

    <div class="settings-container">
        <div class="separator"></div>
        <div
            on:click={handleSettingsClick}
            on:mouseenter={(e) => showTooltip(e, "Settings")}
            on:mouseleave={hideTooltip}
            role="button"
            tabindex="0"
            on:keydown={(e) => e.key === "Enter" && handleSettingsClick()}
        >
            <SidebarItem
                Icon={settings}
                onClick={() => {
                    console.log("xd");
                }}
            />
        </div>
    </div>

    <!-- Global Tooltip -->
    {#if tooltipShow}
        <div
            class="fixed z-60 pointer-events-none"
            style="left: {tooltipX}px; top: {tooltipY}px; transform: translateY(-50%);"
        >
            <SidebarTooltip text={tooltipText} />
        </div>
    {/if}
</div>

<style>
    .sidebar {
        display: flex;
        flex-direction: column;
        align-items: center;
        height: 100%;
        padding: 0.5rem;
        border-right: 1px solid var(--color-border-default);
        background: var(--color-surface);
        transition: all 0.2s ease;
    }

    .logo-container {
        flex-shrink: 0;
        display: flex;
        align-items: center;
        gap: 0.5rem;
        background: var(--color-background);
        border-radius: 0.75rem;
        padding: 0.5rem;
        border: 1px solid var(--color-border-default);
        margin-bottom: 1rem;
        cursor: pointer;
        transition: all 0.2s ease;
    }

    .logo-container:hover {
        background: var(--color-accent-base);
        border-color: var(--color-accent-hover);
        transform: translateY(-1px);
    }

    .logo-container:active {
        transform: translateY(0);
        background: var(--color-accent-active);
    }

    .instances-container {
        flex: 1;
        width: 100%;
        position: relative;
        overflow: hidden;
    }

    .instances-scroll {
        height: 100%;
        overflow-y: auto;
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 1rem;
        padding: 0.5rem 0;
        scrollbar-width: none; /* Firefox */
        -ms-overflow-style: none; /* IE and Edge */
    }

    .instances-scroll::-webkit-scrollbar {
        display: none; /* Chrome, Safari and Opera */
    }

    .separator {
        margin: 0.5rem 1rem;
        width: calc(100% - 2rem);
        height: 1px;
        background: var(--color-border-subtle);
    }

    /* Dark theme specific adjustments */
    .sidebar.dark {
        box-shadow: 2px 0 8px rgba(0, 0, 0, 0.3);
    }

    .sidebar:not(.dark) {
        box-shadow: 2px 0 8px rgba(0, 0, 0, 0.1);
    }

    .add-instance-btn {
        width: 2.5rem;
        height: 2.5rem;
        margin: 0.5rem auto 0.5rem auto;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 1.5rem;
        background: var(--color-accent-base);
        color: #fff;
        border: none;
        border-radius: 50%;
        cursor: pointer;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
        transition: background 0.2s;
    }
    .add-instance-btn:hover {
        background: var(--color-accent-hover);
    }
    .add-instance-btn:active {
        background: var(--color-accent-active);
    }
</style>

// src/components/navigation/Sidebar.vue
<script setup lang="ts">
import { ref } from "vue";
import PlusSquare from "../../assets/icons/UI/plus-square.vue";
import Settings from "../../assets/icons/UI/settings.vue";
import logo from "../../assets/logo.vue";
import { getIcon } from "../../lib/utils";
import { useLanguageStore } from "../../stores/LanguageStore";
import { useLauncherStore } from "../../stores/LauncherStore";
import SidebarItem from "./SidebarItem.vue";
const store = useLauncherStore();
const languageStore = useLanguageStore();

// Logica del tooltip
const tooltipVisible = ref(false);
const tooltipX = ref(0);
const tooltipY = ref(0);
const tooltipText = ref("");

const showTooltip = (
	event: MouseEvent,
	translationKey: string,
	customText?: string,
) => {
	const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
	tooltipX.value = rect.right + 8;
	tooltipY.value = rect.top + rect.height / 2;
	tooltipText.value =
		customText || languageStore.getTranslation(translationKey);
	tooltipVisible.value = true;
};

const hideTooltip = () => {
	tooltipVisible.value = false;
};
</script>

<template>
  <div class="flex flex-col items-center h-full p-2 border-r border-stone-700">
    <!-- Logo -->
    <div
      class="flex-shrink-0 flex items-center gap-2 bg-stone-800 rounded-xl p-2 border border-stone-700 mb-4 cursor-pointer"
      @click="store.CurrentInstance = null">
      <logo class="w-8 h-8"/>
    </div>

    <!-- Main Navigation -->
    <div class="flex-1 w-full relative overflow-hidden">
      <div class="h-full overflow-y-auto flex flex-col items-center gap-2 scrollbar-hide">
        <!-- Separator -->
        <div class="w-8 h-px bg-stone-700 my-1"></div>

        <!-- Instances -->
        <SidebarItem v-for="instance in store.Instances" :key="instance.name" :name="instance.name"
          :icon="getIcon(instance.loader)" @click="store.CurrentInstance = instance" />
      </div>
    </div>

    <!-- Footer -->
    <div class="flex-shrink-0 w-full flex flex-col items-center gap-2">
      <div class="w-8 h-px bg-stone-700 mb-1"></div>

      <!-- Add Instance Button -->
      <div
        class="w-10 h-10 flex items-center justify-center bg-stone-800 rounded-xl border border-stone-700 cursor-pointer hover:bg-stone-700 transition-colors relative"
        @click="store.toggleAddInstanceModal" @mouseenter="showTooltip($event, 'Launcher.sidebar.addInstance')"
        @mouseleave="hideTooltip">
        <PlusSquare />
      </div>

      <!-- Settings Button -->
      <div
        class="w-10 h-10 flex items-center justify-center bg-stone-800 rounded-xl border border-stone-700 cursor-pointer hover:bg-stone-700 transition-colors relative"
        @click="store.toggleSettingsModel" @mouseenter="showTooltip($event, 'Launcher.sidebar.settings')"
        @mouseleave="hideTooltip">
        <Settings />
      </div>
    </div>
  </div>
</template>

<style scoped>
.scrollbar-hide {
  -ms-overflow-style: none;
  scrollbar-width: none;
}

.scrollbar-hide::-webkit-scrollbar {
  display: none;
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
