// src/cubic/components/sidebar/SidebarTooltip.svelte
<script lang="ts">
    import { isDarkTheme } from "../../stores/theme";
    export let text: string | null;
</script>

<div class="tooltip" class:dark={$isDarkTheme}>
    <div class="tooltip-content">
        <span>{text ?? "How did u got here?"}</span>
    </div>
    <!-- Arrow -->
    <div class="tooltip-arrow"></div>
</div>

<style>
    .tooltip {
        position: relative;
        margin-left: 0.5rem;
        background: var(--color-surface);
        color: var(--color-text-primary);
        font-size: 0.75rem;
        padding: 0.5rem 0.75rem;
        border-radius: 0.375rem;
        border: 1px solid var(--color-border-default);
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
        white-space: nowrap;
        backdrop-filter: blur(8px);
        transition: all 0.2s ease;
        z-index: 60;
    }

    .tooltip.dark {
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.4);
    }

    .tooltip-content {
        display: flex;
        align-items: center;
        gap: 0.5rem;
    }

    .tooltip-arrow {
        position: absolute;
        left: -6px;
        top: 50%;
        transform: translateY(-50%);
        width: 0;
        height: 0;
        border-top: 6px solid transparent;
        border-bottom: 6px solid transparent;
        border-right: 6px solid var(--color-surface);
    }

    .tooltip-arrow::before {
        content: "";
        position: absolute;
        left: 1px;
        top: -6px;
        width: 0;
        height: 0;
        border-top: 6px solid transparent;
        border-bottom: 6px solid transparent;
        border-right: 6px solid var(--color-border-default);
    }
</style>

// src/components/navigation/SidebarTooltip.vue
<script setup lang="ts">
defineProps<{
	text: string | null;
}>();
</script>

<template>
  <div
    class="relative ml-2 bg-stone-700 text-white text-xs px-3 py-1 rounded shadow-lg whitespace-nowrap"
  >
    <div class="flex items-center gap-2">
        <span>{{ text? text : "How did u got here?" }}</span>
    </div>
    <!-- Flecha -->
    <div
      class="absolute left-[-6px] top-1/2 -translate-y-1/2 w-0 h-0 border-y-8 border-y-transparent border-r-8 border-r-stone-700"
    ></div>
  </div>
</template>
