// src/cubic/components/modals/Settings/settingsModal.svelte
<script lang="ts">
    import { appStore } from "@stores/launcher";
    import BaseModal from "../base_modal.svelte";
    import Forge from "@components/modals/createInstance/tabs/forge.svelte";
    import About from "@components/modals/Settings/tabs/About.svelte";
    import controller from "@assets/icons/UI/controller.svelte";
    let activeTab = $state("appearance");
    let CurrentTabContent = $state(null);
    const tabs = [
        {
            id: "appearance",
            name: "General",
            icon: controller,
            content: Forge,
        },
        {
            id: "launcher",
            name: "Launcher",
            icon: controller,
            content: Forge,
        },
        {
            id: "about",
            name: "About",
            icon: controller,
            content: About,
        },
    ];
    $effect(() => {
        CurrentTabContent = tabs.find((tab) => tab.id === activeTab)?.content;
    });
    // Handler para click tabs: evitar función inline en template
    function selectTab(id: string) {
        activeTab = id;
        console.log(activeTab);
    }
</script>

<BaseModal isOpen={$appStore.isSettingsModalOpen} title="Settings">
    <div class="flex h-full">
        <nav
            class="w-56 border-r h-full flex flex-col space-y-0.5"
            style="border-color: var(--color-border-default)"
            aria-label="Tabs"
        >
            {#each tabs as { id, name, icon: Icon }}
                <button
                    type="button"
                    onclick={() => selectTab(id)}
                    class={`w-full text-left px-4 py-2.5 text-sm font-medium transition-colors flex items-center gap-2
            ${activeTab === id ? "border-l-2" : "hover:bg-opacity-50"}`}
                    style={activeTab === id
                        ? "background-color: var(--color-surface); color: var(--color-text-primary); border-left-color: var(--color-accent-base);"
                        : "color: var(--color-text-secondary);"}
                    onmouseenter={(e) => {
                        if (activeTab !== id) {
                            e.currentTarget.style.color =
                                "var(--color-text-primary)";
                            e.currentTarget.style.backgroundColor =
                                "var(--color-surface)";
                        }
                    }}
                    onmouseleave={(e) => {
                        if (activeTab !== id) {
                            e.currentTarget.style.color =
                                "var(--color-text-secondary)";
                            e.currentTarget.style.backgroundColor =
                                "transparent";
                        }
                    }}
                    aria-selected={activeTab === id}
                    role="tab"
                    tabindex={activeTab === id ? 0 : -1}
                >
                    <Icon size="24" />
                    {name}
                </button>
            {/each}
        </nav>
        <section class="flex-1 h-full p-2 flex flex-col" role="tabpanel">
            {#if CurrentTabContent}
                <CurrentTabContent />
            {:else}
                <div
                    class="flex items-center justify-center h-full"
                    style="color: var(--color-text-disabled)"
                >
                    No content available for this tab
                </div>
            {/if}
        </section>
    </div>
</BaseModal>

// src/components/modals/Settings/SettingsModal.vue
<template>
  <BaseModal v-model="rosquilla.isSettingsModalOpen" :title="languageStore.getTranslation('Launcher.settings.title')">
    <div class="flex">
      <!-- Vertical Tabs -->
      <div class="w-56 border-r border-[#272727ff]">
        <nav class="flex flex-col space-y-0.5" aria-label="Tabs">
          <button 
            v-for="tab in tabs" 
            :key="tab.id" 
            @click="activeTab = tab.id" 
            :class="[
              activeTab === tab.id
                ? 'bg-[#272727ff] text-[#d6d2d2ff] border-l-2 border-[#78716c]'
                : 'text-[#d6d2d2ff]/60 hover:text-[#d6d2d2ff] hover:bg-[#272727ff]',
              'w-full text-left px-4 py-2.5 text-sm font-medium transition-colors flex items-center gap-2'
            ]"
          >
            <!-- Vue Icon Component -->
            <component 
              :is="tab.icon" 
              class="w-5 h-5"
            />
            
            {{ tab.name }}
          </button>
        </nav>
      </div>

      <!-- Tab Content -->
      <div class="p-2">
        <!-- Dynamic Tab Content -->
        <component 
          :is="getCurrentTabContent()" 
          v-if="getCurrentTabContent()"
          :key="activeTab"
        />
        <div v-else class="flex items-center justify-center h-64 text-stone-400">
          No content available for this tab
        </div>
      </div>
    </div>
  </BaseModal>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useLanguageStore } from "../../../stores/LanguageStore";
import { useLauncherStore } from "../../../stores/LauncherStore";
import BaseModal from "../BaseModal.vue";

// Import tab content components
import LauncherSettings from "./Tabs/LauncherSettings.vue";
import AccountSettings from "./Tabs/AccountSettings.vue";

// Import icons (SVG components)
import controller from "../../../assets/icons/UI/controller.vue";


const rosquilla = useLauncherStore();
const languageStore = useLanguageStore();

const activeTab = ref("general");

// Refactored tabs array with Vue icon components
const tabs = [
	{
		id: "general",
		name: "General",
		icon: controller,
		content: LauncherSettings,
	},
	{
		id: "game",
		name: "Game",
		icon: controller,
		content: LauncherSettings,
	},
	{
		id: "launcher",
		name: "Launcher",
		icon: controller,
		content: LauncherSettings,
	}
];

// Method to get current tab content component
const getCurrentTabContent = () => {
	const currentTab = tabs.find((tab) => tab.id === activeTab.value);
	return currentTab?.content || null;
};
</script>
