// src/components/navigation/SidebarItem.vue
<script setup lang="ts">
import { type Component, ref } from "vue";
import SidebarTooltip from "./SidebarTooltip.vue";

const TooltipShow = ref(false);
const tooltipX = ref(0);
const tooltipY = ref(0);

defineProps<{
	name?: string;
	icon: Component | string;
	onClick?: () => void;
}>();

const showTooltip = (event: MouseEvent) => {
	const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
	tooltipX.value = rect.right + 8;
	tooltipY.value = rect.top + rect.height / 2;
	TooltipShow.value = true;
};

const hideTooltip = () => {
	TooltipShow.value = false;
};

// Helper para verificar si es un string (URL de imagen)
const isImageUrl = (icon: Component | string): icon is string => {
	return typeof icon === "string";
};
</script>

<template>
  <div
    class="flex-shrink-0 flex items-center gap-2 bg-stone-800 rounded-xl p-1 border border-stone-700 cursor-pointer"
    @mouseenter="showTooltip"
    @mouseleave="hideTooltip"
    @click="onClick"
  >
    <!-- Renderizar imagen si es string -->
    <img 
      v-if="isImageUrl(icon)" 
      :src="icon" 
      alt="Icon" 
      class="w-10 h-10 rounded-xl" 
    />
    
    <!-- Renderizar componente si no es string -->
    <component 
      v-else 
      :is="icon" 
      class="w-10 h-10 rounded-xl" 
    />

    <transition name="fade">
      <div
        v-if="TooltipShow"
        class="fixed z-50"
        :style="{ left: tooltipX + 'px', top: tooltipY + 'px', transform: 'translateY(-50%)' }"
      >
        <SidebarTooltip :text="name? name : 'Instance'" />
      </div>
    </transition>
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>

// src/cubic/components/sidebar/SidebarItem.svelte
<script lang="ts">
    import { type Component } from "svelte";
    import SidebarTooltip from "./SidebarTooltip.svelte";
    export let name: string | undefined = undefined;
    export let icon: Component | string;
    export let onClick: (() => void) | undefined = undefined;
    let tooltipShow = false;
    let tooltipX = 0;
    let tooltipY = 0;
    const showTooltip = (event: MouseEvent) => {
        const rect = (
            event.currentTarget as HTMLElement
        ).getBoundingClientRect();
        tooltipX = rect.right + 8;
        tooltipY = rect.top + rect.height / 2;
        tooltipShow = true;
    };
    const hideTooltip = () => {
        tooltipShow = false;
    };
    // Helper to check if it's a string (image URL)
    const isImageUrl = (icon: Component | string): icon is string => {
        return typeof icon === "string";
    };
    const handleClick = () => {
        if (onClick) {
            onClick();
        }
    };
    const handleKeydown = (event: KeyboardEvent) => {
        if (event.key === "Enter" || event.key === " ") {
            event.preventDefault();
            handleClick();
        }
    };
</script>

<div
    class="sidebar-item"
    on:mouseenter={showTooltip}
    on:mouseleave={hideTooltip}
    on:click={handleClick}
    on:keydown={handleKeydown}
    role="button"
    tabindex="0"
>
    <!-- Render image if string -->
    {#if isImageUrl(icon)}
        <img src={icon} alt="Icon" class="icon" />
    {:else}
        <!-- Render component if not string -->
        <svelte:component this={icon} class="icon" />
    {/if}

    <!-- Tooltip -->
    {#if tooltipShow}
        <div
            class="fixed z-50 pointer-events-none"
            style="left: {tooltipX}px; top: {tooltipY}px; transform: translateY(-50%);"
        >
            <SidebarTooltip text={name ?? "Instance"} />
        </div>
    {/if}
</div>

<style>
    .sidebar-item {
        background: var(--color-background);
        padding: 0.25rem;
        border-radius: 0.75rem;
        border: 1px solid var(--color-border-default);
        cursor: pointer;
        transition: all 0.2s ease;
        display: flex;
        align-items: center;
        gap: 0.5rem;
        flex-shrink: 0;
        z-index: 60;
    }

    .sidebar-item:hover {
        background: var(--color-accent-base);
        border-color: var(--color-accent-hover);
        transform: translateY(-1px);
    }

    .sidebar-item:active {
        transform: translateY(0);
        background: var(--color-accent-active);
    }

    .icon {
        width: 2.5rem;
        height: 2.5rem;
        border-radius: 0.75rem;
    }
</style>
